// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdX3fKpJW3AdsuGjoyrJ1Qqg2vKzwAffE',
    appId: '1:722915374991:web:83e14dda63e1bcf05a7dfa',
    messagingSenderId: '722915374991',
    projectId: 'flutter-sample-firebase-start',
    authDomain: 'flutter-sample-firebase-start.firebaseapp.com',
    storageBucket: 'flutter-sample-firebase-start.appspot.com',
    measurementId: 'G-SCL7F68HR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bYRmFJoPP1QKnvsA9wq91AjFsR0pcoE',
    appId: '1:722915374991:android:737dbf2f9dabb8f95a7dfa',
    messagingSenderId: '722915374991',
    projectId: 'flutter-sample-firebase-start',
    storageBucket: 'flutter-sample-firebase-start.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB23LlFXym8u48zv0RzO0bD_kazx5_PZbU',
    appId: '1:722915374991:ios:1f5b6859af6bbbf35a7dfa',
    messagingSenderId: '722915374991',
    projectId: 'flutter-sample-firebase-start',
    storageBucket: 'flutter-sample-firebase-start.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseInstallTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB23LlFXym8u48zv0RzO0bD_kazx5_PZbU',
    appId: '1:722915374991:ios:1f5b6859af6bbbf35a7dfa',
    messagingSenderId: '722915374991',
    projectId: 'flutter-sample-firebase-start',
    storageBucket: 'flutter-sample-firebase-start.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseInstallTest',
  );

}